version: '3'

services:
  db:
    container_name: aswemake
    image: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: market
      MYSQL_ROOT_PASSWORD: mysql
      TZ: 'Asia/Seoul'
    ports:
      - "32775:3306"
    volumes:
      - data_mysqldb:/var/lib/mysqldb
    networks:
      - app-tier
    tty: true

  api-server:
    container_name: api-server
    build:
      context: ./
    command: gradle bootRun
    ports:
      - "8082:8082"
    networks:
      - app-tier
    depends_on:
      - aswemake
    restart: on-failure
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  data_mysqldb: null